// Generated by CoffeeScript 1.10.0
(function() {
  exports.getTypeNames = function(types) {
    var lastType, typeNames;
    if (!(types instanceof Array)) {
      return types.name;
    }
    typeNames = types.map(function(type) {
      return type.name;
    });
    switch (typeNames.length) {
      case 1:
        return typeNames[0];
      case 2:
        return typeNames[0] + " or " + typeNames[1];
      default:
        lastType = typeNames.pop();
        return typeNames.join(", ") + (", or " + lastType);
    }
  };

}).call(this);
